language: en
pipeline: pretrained_embeddings_spacy

policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: FormPolicy
- name: FallbackPolicy
  fallback_action_name: action_default_fallback
